package catalog

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/toolbox-tools/toolbox/internal/yaml"
)

// Catalog is the parsed .toolbox/catalog.yaml.
type Catalog struct {
	Version    int                  `yaml:"version"`
	Runtime    string               `yaml:"runtime,omitempty"` // podman|docker|ssh|auto
	SSH        *SSHConfig           `yaml:"ssh,omitempty"`
	Env        EnvRules             `yaml:"env,omitempty"`
	Containers map[string]Container `yaml:"containers"`
}

// SSHConfig holds remote execution settings.
type SSHConfig struct {
	Host     string `yaml:"host"`
	Identity string `yaml:"identity,omitempty"`
	Port     int    `yaml:"port,omitempty"`
}

// EnvRules controls which host env vars flow into containers.
type EnvRules struct {
	Forward []string `yaml:"forward,omitempty"` // glob patterns to include
	Deny    []string `yaml:"deny,omitempty"`    // glob patterns to exclude (takes priority)
}

// Container is a single entry in the catalog.
type Container struct {
	Image       string            `yaml:"image"`
	Description string            `yaml:"description,omitempty"`
	Handles     []string          `yaml:"handles,omitempty"`
	Env         map[string]string `yaml:"env,omitempty"`
	Fallback    bool              `yaml:"fallback,omitempty"`
}

// Load reads and parses catalog.yaml from the given path.
func Load(path string) (*Catalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("cannot read catalog: %w\nRun `toolbox init` to create one.", err)
	}

	var c Catalog
	if err := yaml.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("invalid catalog.yaml: %w", err)
	}

	if c.Containers == nil {
		return nil, fmt.Errorf("catalog.yaml has no containers defined")
	}

	return &c, nil
}

// Validate checks the catalog for common mistakes.
func (c *Catalog) Validate() []string {
	var errs []string

	hasFallback := false
	for name, ct := range c.Containers {
		if ct.Image == "" {
			errs = append(errs, fmt.Sprintf("container %q has no image", name))
		}
		if ct.Fallback {
			hasFallback = true
		}
	}

	if !hasFallback {
		errs = append(errs, "no fallback container defined — add `fallback: true` to your base container")
	}

	return errs
}

// Fallback returns the name and definition of the fallback container.
func (c *Catalog) Fallback() (string, Container, bool) {
	for name, ct := range c.Containers {
		if ct.Fallback {
			return name, ct, true
		}
	}
	return "", Container{}, false
}

// Resolve returns the best container for the given command string.
// It extracts the primary tool (first token), scans handles[], and falls
// back to the fallback container if nothing matches.
func (c *Catalog) Resolve(command string) (name string, ct Container, err error) {
	primary := primaryTool(command)

	// Scan non-fallback containers first.
	for n, container := range c.Containers {
		if container.Fallback {
			continue
		}
		for _, h := range container.Handles {
			if strings.EqualFold(h, primary) {
				return n, container, nil
			}
		}
	}

	// Fall back.
	n, ct, ok := c.Fallback()
	if !ok {
		return "", Container{}, fmt.Errorf(
			"no container handles %q and no fallback defined in catalog", primary,
		)
	}
	return n, ct, nil
}

// ResolveByName returns the container with the given name, or an error.
func (c *Catalog) ResolveByName(name string) (Container, error) {
	ct, ok := c.Containers[name]
	if !ok {
		available := make([]string, 0, len(c.Containers))
		for n := range c.Containers {
			available = append(available, n)
		}
		return Container{}, fmt.Errorf(
			"container %q not in catalog. Available: %s",
			name, strings.Join(available, ", "),
		)
	}
	return ct, nil
}

// primaryTool extracts the first word of a command, stripping any path prefix.
// "python3 train.py" → "python3"
// "/usr/bin/node server.js" → "node"
func primaryTool(command string) string {
	command = strings.TrimSpace(command)
	if command == "" {
		return ""
	}
	first := strings.Fields(command)[0]
	return filepath.Base(first)
}

// DefaultCatalog returns the YAML for a fresh catalog.yaml.
func DefaultCatalog() string {
	return `# .toolbox/catalog.yaml
# Generated by toolbox init — edit to add specialized containers.
version: 1

# Runtime: auto-detected if omitted (prefers podman, falls back to docker)
# runtime: podman

# Environment variable forwarding from host into containers.
# Glob patterns. Forward rules are checked first, deny rules exclude matches.
env:
  forward:
    - "OPENAI_*"
    - "ANTHROPIC_*"
    - "AWS_*"
    - "AZURE_*"
    - "GOOGLE_*"
    - "DATABASE_*"
    - "REDIS_*"
    - "CI"
    - "DEBUG"
  deny:
    - "HOME"
    - "USER"
    - "SHELL"
    - "TMPDIR"

# Container definitions.
# Add specialized images here as your project needs them.
containers:
  base:
    image: ghcr.io/toolbox-tools/base:latest
    description: "General purpose: python3, node, rg, jq, curl, git, ffmpeg and more"
    fallback: true

  # Uncomment to add browser automation:
  # browser:
  #   image: ghcr.io/toolbox-tools/browser:latest
  #   description: "Web automation: playwright, crawl4ai, chromium"
  #   handles: [playwright, crawl4ai, chromium]

  # Uncomment to add data processing:
  # data:
  #   image: ghcr.io/toolbox-tools/data:latest
  #   description: "Data: duckdb, polars, pandas, numpy"
  #   handles: [duckdb, polars, jupyter]
`
}
